# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 833)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 20, 0, 10)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMaximumSize(QtCore.QSize(1920, 16777215))
        self.Header.setText("")
        self.Header.setPixmap(QtGui.QPixmap("Assets/Header.png"))
        self.Header.setScaledContents(False)
        self.Header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Header.setObjectName("Header")
        self.verticalLayout_2.addWidget(self.Header)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, -1, 9, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.HeaderName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.HeaderName.setFont(font)
        self.HeaderName.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.HeaderName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderName.setObjectName("HeaderName")
        self.gridLayout.addWidget(self.HeaderName, 0, 0, 1, 1)
        self.HeaderMC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.HeaderMC.setFont(font)
        self.HeaderMC.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderMC.setObjectName("HeaderMC")
        self.gridLayout.addWidget(self.HeaderMC, 0, 4, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QWidget > QFrame{\n"
"    border-radius: 4px;\n"
"    border: 2px solid #30D5C8;\n"
"}\n"
"QWidget > QFrame QLabel{\n"
"    border: none;\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1097, 353))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.scrollAreaWidgetContents_2.setFont(font)
        self.scrollAreaWidgetContents_2.setStyleSheet("")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.N = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N.sizePolicy().hasHeightForWidth())
        self.N.setSizePolicy(sizePolicy)
        self.N.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.N.setFont(font)
        self.N.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.N.setObjectName("N")
        self.gridLayout_2.addWidget(self.N, 0, 0, 1, 1)
        self.MC = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MC.setFont(font)
        self.MC.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MC.setObjectName("MC")
        self.gridLayout_2.addWidget(self.MC, 0, 4, 1, 1)
        self.H24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.H24.setFont(font)
        self.H24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.H24.setObjectName("H24")
        self.gridLayout_2.addWidget(self.H24, 0, 2, 1, 1)
        self.P = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.P.setFont(font)
        self.P.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.P.setObjectName("P")
        self.gridLayout_2.addWidget(self.P, 0, 1, 1, 1)
        self.D7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.D7.setFont(font)
        self.D7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.D7.setObjectName("D7")
        self.gridLayout_2.addWidget(self.D7, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 5)
        self.Header24h = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header24h.sizePolicy().hasHeightForWidth())
        self.Header24h.setSizePolicy(sizePolicy)
        self.Header24h.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.Header24h.setFont(font)
        self.Header24h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Header24h.setObjectName("Header24h")
        self.gridLayout.addWidget(self.Header24h, 0, 2, 1, 1)
        self.HeaderPrice = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.HeaderPrice.setFont(font)
        self.HeaderPrice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderPrice.setObjectName("HeaderPrice")
        self.gridLayout.addWidget(self.HeaderPrice, 0, 1, 1, 1)
        self.Header7d = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.Header7d.setFont(font)
        self.Header7d.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Header7d.setObjectName("Header7d")
        self.gridLayout.addWidget(self.Header7d, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.Back.setFont(font)
        self.Back.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(48, 213, 200);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px 100px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(8, 232, 222);\n"
"}")
        self.Back.setObjectName("Back")
        self.horizontalLayout.addWidget(self.Back)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.Next.setFont(font)
        self.Next.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(48, 213, 200);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px 100px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(8, 232, 222);\n"
"}")
        self.Next.setObjectName("Next")
        self.horizontalLayout.addWidget(self.Next)
        spacerItem2 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.Filter = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        self.Filter.setFont(font)
        self.Filter.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}\n"
"QLineEdit{\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #30D5C8;\n"
"}")
        self.Filter.setObjectName("Filter")
        self.verticalLayout_2.addWidget(self.Filter)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HeaderName.setText(_translate("MainWindow", "Name"))
        self.HeaderMC.setText(_translate("MainWindow", "Market Cap"))
        self.N.setText(_translate("MainWindow", "Names"))
        self.MC.setText(_translate("MainWindow", "hfghf"))
        self.H24.setText(_translate("MainWindow", "fgd"))
        self.P.setText(_translate("MainWindow", "Prices"))
        self.D7.setText(_translate("MainWindow", "fghfdh"))
        self.Header24h.setText(_translate("MainWindow", "24h %"))
        self.HeaderPrice.setText(_translate("MainWindow", "Price"))
        self.Header7d.setText(_translate("MainWindow", "7d %"))
        self.Back.setText(_translate("MainWindow", "BACK"))
        self.Next.setText(_translate("MainWindow", "NEXT"))
        self.Filter.setPlaceholderText(_translate("MainWindow", "Search by name"))
